### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kejdene** [Vins95/DELL-Inspiron-7391-Hackintosh-EFI-#1]
Hi guys hope you are doing good. First at all i want to really thank u for the work you provided. it's really great to have persons like u in the communitte. it's been now almost tow months that i try to built a hakintosh on my laptop dell inspiron 7391. And i think your EFI works perfectly but i have a problem just afer the vermoz mode. I only have a light on my screen and I can't see anything. however i know the boot has worked cause i can hear the song when i plugge the computer on power. If you can help me I will be grateful to you. We have exactly the same model and i use the same EFI. How to solve this graphic problem?

**Comment by Vins95** [comment]
@kejdene Hi Kejdene! try to use bootargs igfxonly=1

**Comment by kejdene** [comment]
@Vins95 Hi .......  i try but it does't work, same problem, only light on screen. Maybe it is a problem of my BIOS config or  kexts ?

**Comment by Vins95** [comment]
@kejdene let me understand, you start and after the verbif you have black screen? however, update the bios to version 1.10.0

**Comment by kejdene** [comment]
@Vins95  i dont exactly have a black screen, i have low light almost blue .. i thought this was the problem so i updated my bios to 1.10.0 but unfortunately nothing has changed. I will keep trying things.

**Comment by Vins95** [comment]
@kejdene try to press F6 for increase brightness

**Comment by Vins95** [comment]
or try to going in System Preferenceì/Monitor and increase manually the brightness with the Bar level

**Comment by Vins95** [comment]
for support going in the telegram Group hackintoshLifeIT https://t.me/HackintoshLife_it

**Comment by kejdene** [comment]
Ok i will try to increase light ........... got it, if i does't work, i am  gonna see in the telegram group... Thanks for your reply .. Stay safe
